### ISSUE TITLE
SI_FACTOR value not explained

### ISSUE THREAD

**Issue by 4gra** [4gra/FreeStyleLibre-NFC-Reader#1]
@hferreira writes (in https://github.com/4gra/icalreport/issues/1), "How do you came with the SI FACTOR 0.05551 on this project https://github.com/4gra/FreeStyleLibre-NFC-Reader ?"

**Comment by 4gra** [comment]
The answer has now been added to 
https://github.com/4gra/FreeStyleLibre-NFC-Reader/blob/master/README.md but I really ought to put a brief comment into the code, too.

**Comment by hferreira** [comment]
Thank you !
